Repository yiisoft/yii-bulma, pull requests merged in 2020-11, with the labels that each got.

#11 Proposal remove npm dependency
  .github/workflows/build.yml
  .github/workflows/mutation.yml
  .github/workflows/static.yml
  composer.json
  package.json
  src/Asset/BulmaAsset.php
  src/Asset/BulmaJsAsset.php
  src/Asset/FilePluginAsset.php
  src/Asset/MessagePluginAsset.php
Labels: status:code review

#13 Enhacements.
  .github/workflows/build.yml
  .github/workflows/mutation.yml
  .github/workflows/static.yml
  .scrutinizer.yml
  composer.json
  src/Menu.php
  src/Nav.php
  src/NavBar.php
Labels: status:code review

#14 Cleanup
  phpunit.xml.dist
  psalm.xml
  src/Breadcrumbs.php
  src/Dropdown.php
  src/Menu.php
  src/Message.php
  src/Nav.php
  src/NavBar.php
  src/Widget.php
  tests/BreadcrumbsTest.php
  tests/NavTest.php
Labels: status:code review

#15 More docs and better naming
  docs/breadcrumbs.md
  src/Breadcrumbs.php
  src/Dropdown.php
  src/Menu.php
  src/Message.php
  src/NavBar.php
  tests/BreadcrumbsTest.php
Labels: status:code review

#16 Update dev dependencies, pipelines and scrutinizer.
  .github/workflows/bc.yml_
  .github/workflows/build.yml
  .github/workflows/mutation.yml
  .github/workflows/static.yml
  .scrutinizer.yml
  README.md
Labels: status:code review

#19 Add progress bar widget
  README.md
  docs/breadcrumbs.md
  docs/dropdown.md
  docs/images/progressbar-indeterminate.gif
  docs/images/progressbar.png
  docs/menu.md
  docs/message.md
  docs/navbar.md
  docs/progressbar.md
  src/ProgressBar.php
  tests/ProgressBarTest.php
Labels: status:under development, type:feature

#20 Add Modal widget
  README.md
  docs/modal.md
  docs/modalcard.md
  src/Modal.php
  src/ModalCard.php
  tests/ModalCardTest.php
  tests/ModalTest.php
Labels: type:enhancement
